distribution_of_total_ship_count_by_days = f"""
    SELECT O.MOORAGE_DATE AS DATE, COUNT(*) AS TOTAL 
    FROM PORTDATA.DBO.V_TBL_ORDERS O INNER JOIN PORTDATA.DBO.V_TBL_SHIPS S ON O.SHIP_KEY = S.SHIP_KEY
    WHERE O.MOORAGE_DATE IS NOT NULL
    GROUP BY O.MOORAGE_DATE 
    ORDER BY O.MOORAGE_DATE
"""